import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/providers/ThemeProvider";
import Nav from "@/components/section/Nav";
import SessionProvider from "@/providers/SessionProvider";
import PaypalProvider from "@/providers/PayPalProvider";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
      >
        <SessionProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <PaypalProvider>
               <Nav />
              {children}
              </PaypalProvider>
            </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
